{% set name = "keystoneauth1" %}
{% set version = "5.2.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f79b1c27ed5a69be4d03a5bc4967df3dfab0c5d76e85226fa2060cffadff74a1

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python >=3.8
    - pip
    - pbr !=2.1.0,>=2.0.0

  run:
    - python >=3.8
    - pbr !=2.1.0,>=2.0.0
    - iso8601 >=0.1.11
    - requests >=2.14.2
    - stevedore >=1.20.0
    - os-service-types >=1.2.0

test:
  imports:
    - keystoneauth1
    - keystoneauth1.identity
    - keystoneauth1.identity.v2
    - keystoneauth1.identity.v3
    - keystoneauth1.identity.generic
    - keystoneauth1.extras

about:
  home: https://docs.openstack.org/developer/keystoneauth/
  license_file: LICENSE
  license: Apache-2.0
  license_family: Apache
  summary: Authentication Library for OpenStack Identity
  dev_url: https://git.openstack.org/cgit/openstack/keystoneauth
  doc_url: https://docs.openstack.org/developer/keystoneauth/

extra:
  recipe-maintainers:
    - pmlandwehr
    - tschoonj
