{% set name = "keystoneauth1" %}
{% set version = "3.13.0" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "eea3bf0d6de0f1e965f7162f82ea1a8394af3cb7b33e67c6227189b48344f207" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - pbr !=2.1.0,>=2.0.0

  run:
    - python
    - pbr !=2.1.0,>=2.0.0
    - iso8601 >=0.1.11
    - requests >=2.14.2
    - six >=1.10.0
    - stevedore >=1.20.0
    - os-service-types >=1.2.0
    
test:
  imports:
    - keystoneauth1
    - keystoneauth1.identity
    - keystoneauth1.identity.v2
    - keystoneauth1.identity.v3
    - keystoneauth1.identity.generic
    - keystoneauth1.extras

about:
  home: https://docs.openstack.org/developer/keystoneauth/
  license_file: LICENSE
  license: Apache 2.0
  license_family: Apache
  summary: Authentication Library for OpenStack Identity
  dev_url: https://git.openstack.org/cgit/openstack/keystoneauth
  doc_url: https://docs.openstack.org/developer/keystoneauth/

extra:
  recipe-maintainers:
    - pmlandwehr
